[[main]]
none = "none"

[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 10


[[main]]
pre = "email"
url = "mailto:jasvpj@gmail.com"
identifier = "o2qDWq7SRB"
weight = 9999

[[main]]
name = "Autores"
url = "/authors"
weight = 9

[[main]]
name = "Videos"
url = "/playlist"
weight = 8

[[footer]]
none = "none"
