[[main]]
none = "none"

[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 10


[[main]]
pre = "email"
url = "mailto:jasvpj@gmail.com"
identifier = "o2qDWq7SRB"
weight = 9999

[[footer]]
none = "none"
